const libraries: string[] = [
    'Arvonne Fraser Library',
    'Augsburg Park Library',
    'Brookdale Library',
    'Brooklyn Park Library',
    'Champlin Library',
    'East Lake Library',
    'Eden Prairie Library',
    'Edina Library',
    'Excelsior Library',
    'Franklin Library',
    'Golden Valley Library',
    'Hopkins Library',
    'Hosmer Library',
    'Linden Hills Library',
    'Long Lake Library',
    'Maple Grove Library',
    'Maple Plain Library',
    'Minneapolis Central Library',
    'Minnetonka Library',
    'Nokomis Library',
    'North Regional Library',
    'Northeast Library',
    'Osseo Library',
    'Oxboro Library',
    'Penn Lake Library',
    'Pierre Bottineau Library',
    'Plymouth Library',
    'Ridgedale Library',
    'Rockford Road Library',
    'Rogers Library',
    'Roosevelt Library',
    'St. Anthony Library',
    'St. Bonifacius Library',
    'St. Louis Park Library',
    'Southdale Library',
    'Sumner Library',
    'Walker Library',
    'Washburn Library',
    'Wayzata Library',
    'Webber Park Library',
    'Westonka Library'
];

export default libraries;
